version: "3.7"
services:
  back-proyecto:
    container_name: back-proyecto
    image: back-proyecto:v1
    build:
      context: .
    ports:
      - "4001:4001"
    networks:
      - proyecto-app 
networks:
  proyecto-app: